Importing the Packages

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

Reading the CSV files and making it as Workable file (Not Required)

In [2]:
red_wine_data = pd.read_csv('winequality-red.csv')
white_wine_data = pd.read_csv('winequality-white.csv')

In [3]:
red_wine = []
red_wine_col = red_wine_data.columns[0].split(';')
white_wine = []
white_wine_col = white_wine_data.columns[0].split(';')
for i in range(len(red_wine_data)):
  red_wine.append(red_wine_data.values[i][0].split(';'))
for i in range(len(white_wine_data)):
  white_wine.append(white_wine_data.values[i][0].split(';'))

In [4]:
import csv

with open('wine-red.csv', 'w') as file:
  sw = csv.writer(file)
  sw.writerow(red_wine_col)
  sw.writerows(red_wine)

with open('wine-white.csv', 'w') as file:
  sw = csv.writer(file)
  sw.writerow(white_wine_col)
  sw.writerows(white_wine)

Reading the Organized CSV File

In [10]:
red_data = pd.read_csv('wine-red.csv')
white_data = pd.read_csv('wine-white.csv')

Importing ML Model Libraries

In [9]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

Splitting the Red Wine Dataset as Features and Target

In [11]:
red_X = red_data.iloc[:, :-1].values
red_y = red_data.iloc[:, -1].values

array([5, 5, 5, ..., 6, 5, 6])

Splitting it further into Training and Test Set

In [12]:
red_X_train, red_X_test, red_y_train, red_y_test = train_test_split(red_X, red_y, test_size=0.2, random_state=0)


array([[ 9.9 ,  0.54,  0.45, ...,  3.39,  0.62,  9.4 ],
       [10.8 ,  0.26,  0.45, ...,  3.13,  0.54,  9.6 ],
       [ 9.9 ,  0.35,  0.55, ...,  3.26,  0.79, 10.6 ],
       ...,
       [ 7.9 ,  0.57,  0.31, ...,  3.29,  0.69,  9.5 ],
       [13.  ,  0.47,  0.49, ...,  3.3 ,  0.68, 12.7 ],
       [ 9.8 ,  0.98,  0.32, ...,  3.25,  0.48,  9.4 ]])

Creating a Model for Red Wine Data

In [17]:
red_lr = LinearRegression()
red_lr.fit(red_X_train, red_y_train)


array([10.8   ,  0.47  ,  0.43  ,  2.1   ,  0.171 , 27.    , 66.    ,
        0.9982,  3.17  ,  0.76  , 10.8   ])

Predicting the Red Wine Quality for Random User Value

Making the Worst possible Red Wine with the below combinations.

Fixed Acidity at **14.0**, 
Volatile Acidity at **0.4**, 
Citric Acid at **0.7**, 
Residual Sugar at **2**, 
Chlorides at **1**, 
Free Sulfur Dioxide at **1**,  
Total Sulfur Dioxide at **50**, 
Density at **1.0100**, 
pH at **3.3**, 
Sulphates at **0.4**, 
Alcohol at **1**, 



In [33]:
print(f"Red Wine Quality is {round(red_lr.predict([[14.0, 0.4, 0.7, 2, 1, 1, 50, 1.0100, 3.3, 0.4, 1]])[0])}")

Wine Quality is 1


Doing the same for White Wine

Splitting the Data as Features and Target

In [35]:
white_X = white_data.iloc[:, :-1].values
white_y = white_data.iloc[:, -1].values

Again, splitting it as Training and Test Set

In [36]:
white_X_train, white_X_test, white_y_train, white_y_test = train_test_split(white_X, white_y, test_size=0.2, random_state=0)

Creating a Model for White Wine

In [38]:
white_lr = LinearRegression()
white_lr.fit(white_X_train, white_y_train)

LinearRegression()

Predicting the Quality of White Wine using the Created Model

Data is given below

Fixed Acidity at **7**, 
Volatile Acidity at **0.2**, 
Citric Acid at **0.15**, 
Residual Sugar at **10**, 
Chlorides at **0.05**, 
Free Sulfur Dioxide at **50**,  
Total Sulfur Dioxide at **200**, 
Density at **0.9999**, 
pH at **2.9**, 
Sulphates at **0.7**, 
Alcohol at **10**,

In [40]:
print(f"White Wine Quality is {round(white_lr.predict([[7, 0.2, 0.15, 10, 0.05, 50, 200, 0.9999, 2.9, 0.7, 10]])[0])}")

White Wine Quality is 5
